<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos [
  <!ELEMENT alumnos (alumno*)>
  <!ELEMENT alumno (nombre, apellido, curso)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
  <!ELEMENT curso (#PCDATA)>

  <!ATTLIST alumno
    id ID #REQUIRED
    edad CDATA #IMPLIED
    becado (si|no) "no"
  >
]>

<alumnos>
  <alumno id="a1" edad="20" becado="si">
    <nombre>Eros</nombre>
    <apellido>Jaeger</apellido>
    <curso>Matemáticas</curso>
  </alumno>
  <alumno id="a2" edad="21">
    <nombre>Mikasa</nombre>
    <apellido>Ackerman</apellido>
    <curso>Historia</curso>
  </alumno>
  <alumno id="a3" edad="30" becado="si">
    <nombre>Armin</nombre>
    <apellido>Arlert</apellido>
    <curso>Física</curso>
  </alumno>
  <alumno id="a4" edad="26" becado = "no">
    <nombre>Levi</nombre>
    <apellido>Yacker</apellido>
    <curso>Química</curso>
  </alumno>
</alumnos>